version: '3'
services:
  titan:
    # restart: always
    build: .
    volumes:
      - .:/titan/src/Titan:rw
    links:
      - postgresql
    ports: # you can comment this out when using the nginx frontend
      - 5555:5555
  postgresql:
    restart: always
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - ./_volumes/postgresql:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: titan
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password


